Handle EOF from multipart form file readers
go-resty/resty pull request #438
Opened 2021-07-15 01:30 UTC by NathanBaulch

I stumbled on a bug when trying to send a multipart file that happened to be a gzip reader downloaded from elsewhere. Looks like the multipart content type detection logic doesn't handle `EOF` correctly. This can also be easily reproduced by sending an empty file (`bytes.NewReader(nil)`).

```go
b := bytes.NewBuffer(nil)
w := gzip.NewWriter(b)
if _, err := w.Write([]byte("foo")); err != nil {
	panic(err)
}
if err := w.Close(); err != nil {
	panic(err)
}
r, err := gzip.NewReader(b)
if err != nil {
	panic(err)
}
_, err = resty.New().NewRequest().SetFileReader("file", "foo.bar", r).Post("http://foo.bar")
if err != nil {
	panic(err) // EOF!
}
```

2021-07-30 23:11 UTC, NathanBaulch commented
Bump @jeevatkm

2021-09-12 00:33 UTC, jeevatkm commented
@NathanBaulch Thanks for your PR appreciated it! 

Travis CI build link was broken. I have migrated travis-ci.org to travis-ci.com

Can you please edit the PR to trigger the CI build?

2021-09-12 02:52 UTC, jeevatkm requested changes
@NathanBaulch It seems the test case is not covered for this PR update, can you please take a look at it?

https://app.codecov.io/gh/go-resty/resty/compare/438/diff#diff-dXRpbC5nbw==

2021-09-12 10:51 UTC, NathanBaulch commented
The test case doesn't increase coverage because my fix is all about avoiding a false error. There is no new code path that the test could hit.

The test fails without the fix, passes with the fix and doesn't impact coverage, as expected. Hopefully that makes sense.

2021-09-12 16:46 UTC, jeevatkm commented
@NathanBaulch Yes, it makes sense.
Actually, I was aiming to get coverage for the "error happened before reaching EOF" use case.

2021-09-12 23:35 UTC, NathanBaulch commented
Not really relevant to my fix but sure, I've added a test that borrows `brokenReadCloser` from the request tests.

2021-09-13 04:57 UTC, jeevatkm commented
Closes #431

2021-09-13 17:21 UTC, jeevatkm approved these changes
@NathanBaulch Thanks for your PR.

2021-09-13 17:23 UTC, merged