Fix multipart file readers not being reset when doing a retry
go-resty/resty pull request #549
Opened 2022-06-15 10:37 UTC by nikplx

As mentioned in https://github.com/go-resty/resty/issues/166 by @neganovalexey, when doing a retry on a multipart request the `io.Reader` is not reset to the start again. This can lead to subtle bugs, as the request will be retried, but the form part of the file will be empty, because the reader was already exhausted. Solving this issue in the caller code is pretty ugly, because `Request` does not expose access to `multipartFiles` and so the caller would have to use `RetryHooks` and recreate the `Response.Request` and that at each call site (where there is access to the original `ReadSeeker`).

In the PR, I made the `Backoff` function seeking the start of each reader in `multipartFiles`, if the reader it got also implements `io.ReadSeeker`. This solved the above issue described above for my usecase and should have minimal implications on existing usages.

2022-06-15 17:00 UTC, SVilgelm commented
What about the readers that cannot be reset?

2022-06-21 11:20 UTC, nikplx commented
@SVilgelm 
They won't be reset. The code only resets the reader if it implements `io.ReadSeeker` and that only if you enable it, so as to not break any running code. Every other reader will be untouched. I don't know if there is a usecase for passing in a reader that should not be reset, but it will not do anything if there is a reader that can not be reset.

2023-03-06 00:35 UTC, jeevatkm commented
@nikplx I'm sorry for the delayed attention on the PR. Thanks for your contribution.

2023-03-06 00:45 UTC, jeevatkm commented
@nikplx I'm sorry for the delayed attention on the PR. Thanks for your contribution.
Yes, it make sense to provide the reset readers option for resty users.

2023-03-06 00:46 UTC, jeevatkm requested changes
@nikplx Can you please help to get the PR build validation cleared? then we can merge this PR.

2023-03-06 00:46 UTC, jeevatkm commented on client.go
> +// Since ...
I will fill in the version in before the release.

2023-03-06 07:38 UTC, nikplx commented
Hey @jeevatkm 

I fixed the test stage. There was some mixup in the sum file. It now runs locally. Maybe you can retrigger the pipeline if you have some time.

2023-03-06 09:34 UTC, jeevatkm commented
@nikplx This time PR validation build executed without any issue.

Do you mind checking this [codecov feedback](https://github.com/go-resty/resty/pull/549/checks?check_run_id=11786008284)?

2023-03-08 04:42 UTC, jeevatkm approved these changes
Thanks @nikplx 👍

2023-03-08 04:43 UTC, merged