Fix redirect body reuse buffer by mistake
go-resty/resty pull request #568
Opened 2022-07-26 13:23 UTC by liguangbo

As issue #567 described.

Copy the body buffer by buffer.Write to fix body mismatch with origin request when 307 or 308 redirect.

2022-07-28 02:01 UTC, liguangbo commented
Anyone can help？ 
It's a serious problem in some cases, such as user A POST user B's data to server, and lost user A's data.

@jeevatkm

2022-09-22 22:19 UTC, thalesfsp commented
@jeevatkm Sept 22

2022-09-29 12:30 UTC, segevda requested changes
Very nice catch!

2022-09-29 12:30 UTC, segevda commented on client_test.go
> +			assertNil(t, err)
you can use assertError instead of assertNil here

2022-09-29 12:30 UTC, segevda commented on resty_test.go
> +
maybe switch on r.URL.Path (like what's done on createGetServer)

2022-10-01 06:44 UTC, segevda commented on middleware.go
> +		bodyCopy.Write(r.bodyBuf.Bytes())
there's an unhandled error here. Anyway, I think it's clearer if we use io.Copy here instead

2022-10-08 05:43 UTC, liguangbo commented
@segevda thanks for the review

2022-10-31 06:32 UTC, segevda approved these changes

2023-02-28 14:16 UTC, bbrodriges commented
@segevda will this fix be merged? This bug affects our production code.

2023-03-01 07:03 UTC, segevda commented
@bbrodriges unfortunately I don't have merge capabilities for this repo. Maybe @jeevatkm or @moorereason can take a look..?

2023-03-08 04:50 UTC, jeevatkm approved these changes
Thanks @liguangbo, I have updated the line.

2023-03-08 04:51 UTC, merged

2023-03-16 12:46 UTC, liguangbo commented
@jeevatkm Sorry for didn't see the notification. Happy to contribute to resty.