fix: parseResponseBody overrides original error code in case of unmar…
go-resty/resty pull request #674
Opened 2023-06-27 06:59 UTC by dmartinol

This closes #673

I'm not sure what is the best practice to notify of the swallowed marshalling error, anyway I think we cannot override the original error received from the server because of that. Please let me know your feedback about this fix.

**Note**: I found this issue while using [gocloak](https://github.com/Nerzal/gocloak) the go client for Keycloak. Un fact, the latest versions of Keycloak have changed the response data for the 404/Not Found responses, and the body is empty instead of containing a JSON document, so the get requests fail with this `unexpected end of JSON input` error hiding the 404 status code, which is not acceptable.

2023-07-20 18:27 UTC, renathoaz commented
@dmartinol if you could do this small change too I will appreciate. Thank you in advance
https://github.com/go-resty/resty/issues/673#issuecomment-1644390362

2023-09-17 06:36 UTC, jeevatkm requested changes

2023-09-17 06:36 UTC, jeevatkm commented on middleware.go
> +					log.Printf("[WARN] Cannot unmarshal response body: %s", unmarshalErr)
@dmartinol can you update this line as following?
```go
c.log.Warnf("Cannot unmarshal response body: %s", unmarshalErr)
```

2023-09-19 04:19 UTC, jeevatkm approved these changes
Thanks, @dmartinol, for updating the PR.

2023-09-19 04:30 UTC, merged